name: refresh

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set Git Identity
        run: |
          git config --global user.name "Sumorio"
          git config --global user.email "ambor0225@gmail.com"

      - name: Git Remote Setup
        run: git remote set-url origin https://x-access-token:${TOKEN}@github.com/Sumorio/BlogPic.git

      - name: CDN Refresh Trigger
        run: |
          git commit --allow-empty -m "CDN refresh trigger"
          git push origin main
