name: CDN refresh trigger

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 零点（北京时间早上8点）
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Refresh CDN (jsDelivr)
        run: |
          echo "刷新时间：$(date)" >> refresh.log

      - name: Commit and Push
        run: |
          git add refresh.log
          git commit -m "chore: trigger jsDelivr CDN refresh [skip ci]" || echo "Nothing to commit"
          git push --force-with-lease "https://${{ secrets.BLOGPIC_PAT }}@github.com/Sumorio/BlogPic.git" HEAD:main
