name: Refresh CDN

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 每天北京时间 11 点自动运行（UTC+8）

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Make a refresh log
        run: |
          echo "Refresh run at $(date)" >> refresh.log
          git add refresh.log
          git commit -m "chore: trigger jsDelivr CDN refresh [skip ci]" || echo "Nothing to commit"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main || echo "Nothing to rebase"

      - name: Push changes
        run: |
          git push "https://${{ secrets.BLOGPIC_PAT }}@github.com/Sumorio/BlogPic.git" HEAD:main
