name: test push

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Test push
        run: |
          date >> push-test.log
          git add push-test.log
          git commit -m "test: push via PAT" || echo "Nothing to commit"
          git push --force-with-lease "https://${{ secrets.BLOGPIC_PAT }}@github.com/Sumorio/BlogPic.git" HEAD:main
