name: Refresh CDN

on:
  schedule:
    - cron: '0 8 * * *' # 每天早上 8 点刷新
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Refresh timestamp: $(date -u)" > refresh.log

      - name: Commit & Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: trigger jsDelivr CDN refresh [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
