name: Refresh CDN

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run something
        run: |
          # 处理图片或刷新缓存
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "refresh CDN cache [skip ci]"
          git push
