name: Refresh CDN

on:
  schedule:
    - cron: '0 8 * * *' # 每天早上 8 点刷新
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commit README to refresh CDN
        run: |
          echo "Refresh timestamp: $(date -u)" > README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add README.md
          git commit -m "chore: trigger jsDelivr CDN refresh"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Sumorio/BlogPic.git HEAD:main
