name: Refresh CDN

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # 每天早上 8 点触发

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ⚠️ 一定不能省略！防止 push 报错

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Touch refresh.log
        run: |
          echo "Refresh timestamp: $(date -u)" >> refresh.log

      - name: Commit and Push
        run: |
          git add refresh.log
          git commit -m "chore: trigger jsDelivr CDN refresh [skip ci]" || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Sumorio/BlogPic.git" HEAD:main
